### PR TITLE
Ported to Paket/Fake

### PR DESCRIPTION
**Pull request by voronoipotato**
Ported to Paket/Fake. XUnit had some trouble with the newer Fsharp.Core bindings but otherwise things went smoothly. This library may be interesting to use with FSound.

### CODE REVIEW

**Comment by voronoipotato** [comment]
I guess I'll need to update the travis-ci script

**Comment by pedromsantos** [comment]
Hi, thank you for the pull request.I was not aware of FSound will check it out. If you can update the travis-ci script I will merge the PR.

**Comment by voronoipotato** [comment]
Alright, will do probably tonight. I might make a glue project between Vaughan and FSound.

**Comment by pedromsantos** [comment]
Sounds amazing thank you for your contribution :)

**Comment by voronoipotato** [comment]
it looks like it failed before my script even ran. 
"
 This job ran on our Trusty environment, which has been updated on Tuesday, December 12th, 2017. Read all about this on our blog and take note that you can add group: deprecated-2017Q4 in your .travis.yml file to use the previous image version.
"

**Comment by voronoipotato** [comment]
okay this one the only failing bit was 
"
The command "dotnet nuget push ./Vaughan/Vaughan.*.nupkg -k $NugetApiKey -s https://www.nuget.org/" exited with 1.
"

which is as expected

**Pull request merged**
